logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            nodeValue: TRACE
    root: INFO
spring:
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
      routes[2]:
        uri: http://localhost:8761
        filters[0]: SetPath=/
        id: discovery-server
        predicates[0]: Path=/eureka
      routes[0]:
        id: elemental-app
        uri: lb://elemental-app
        predicates[0]: Path=/elemental/**
      routes[1]:
        id: elemental-chat
        predicates[0]: Path=/message/**
        uri: lb://elemental-chat

  application:
    name: api-gateway
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
